### ISSUE TITLE
Authetication error, run the 'ocm login' command

### ISSUE THREAD

**Issue by T0MASD** [openshift/osdctl#146]
I'm getting a login error with osdctl version 0.5.0, GitCommit: e5b4ae
```
[~ {production} ]$ ocm whoami | grep username
  "username": "***"
[~ {production} ]$ osdctl servicelog list 3cbf516c-d432-4ad3-9c5c-596365e3d7c3
FATA[0000] Failed to create OCM connection: Authetication error, run the 'ocm login' command first.
```
The error went away after I've `cp ~/.config/ocm/ocm.json ~/.ocm.json` 
To fix this please bump ocm sdk version for osdctl

**Comment by georgettica** [comment]
This is a known ocm-cli issue

The config file default location has changed and some tools have the ocm-cli too old, so it doesn't find the file

To fix this you just need to bump ocm-cli to latest

**Comment by georgettica** [comment]
@tomason with the new release of osdctl (v0.7.0),  the two are aligned to use the `~/.config/ocm/ocm.json` path

**Comment by georgettica** [comment]
(sorry for pulling the wrong Tomas in)

**Comment by T0MASD** [comment]
Confirming `osdctl servicelog list` works as expected using osdctl version 0.7.0, GitCommit: bb55118
