### ISSUE TITLE
osdctl shouldn't require a running kubernetes cluster for unit tests

### ISSUE THREAD

**Issue by iamkirkbater** [openshift/osdctl#163]
Tests in osdctl should be refactored to not require a running kubernetes cluster for unit tests to run, and should instead require a mock of the same.

**Comment by fahlmant** [comment]
This is already tracked here https://issues.redhat.com/browse/OSD-8708

**Comment by georgettica** [comment]
and there is a PR here #165

**Comment by georgettica** [comment]
Please verify the issue has been resolved and close it.

PR merged

**Comment by georgettica** [comment]
@fahlmant can this be closed?

**Comment by fahlmant** [comment]
Is the issue solved? If not, is there an OSD?

**Comment by georgettica** [comment]
Please read up the thread, you noted the OSD XD

**Comment by fahlmant** [comment]
Looks done, closing.
