### ISSUE TITLE
ServiceLog submission should include clusterID and subscriptionID

### ISSUE THREAD

**Issue by tiwillia** [openshift/osdctl#164]
When submitting a serviceLog, only the clusterUUID is provided. This results in the possibility of receiving a 403 from OCM for some users when the cluster with the given clusterUUID has not completed installation successfully. Including the clusterID and subscriptionID in the POST request will ensure that the authz mechanism can find the subscription/cluster record for the matching clusterUUID even if metrics have never been sent by the cluster.

See https://github.com/openshift/osdctl/blob/master/cmd/servicelog/post.go#L333

The service log post operation already lists the cluster record and already  has access to both the clusterID and the subscriptionID from the cluster record: https://github.com/openshift/osdctl/blob/master/cmd/servicelog/list.go#L38

**Comment by petli-openshift** [comment]
Here's an example for adding the additional fields,
```
POST /api/service_logs/v1/cluster_logs
{
  "cluster_uuid": "f07ee822-5710-4771-9bbd-7a81b08d8996",
  "cluster_id": "1MKVU4otCIuogoLtgtyU6wajxjW",                  // OCM cluster ID. It is optional but recommended to ensure the request succeed even the cluster fails provisioning in OCM
  "subscription_id": "20eYVot1AWhNSeJmr9QmGt4Kn2W",  // OCM subscription ID. It is optional but recommended for the same reason.
  "service_name": "AccountManager",
  "severity": "Debug",
  "summary": "test summary",
  "description": "test description",
  "event_stream_id": "test-stream-id",
  "internal_only": false
}
```

**Comment by petli-openshift** [comment]
does not need to be both. Either cluster_id or subscription_id should suffice

**Comment by georgettica** [comment]
#174 seems to solve this

Should we add this to the card?

**Comment by georgettica** [comment]
Soon there will be a prod release for servicelogs
I'll update once that hits and check this

**Comment by tiwillia** [comment]
@georgettica Just trying to revive this. Its likely still necessary, not sure what prod release was being waited on.
