### ISSUE TITLE
osdctl should complain if it's too old

### ISSUE THREAD

**Issue by mmazur** [openshift/osdctl#176]
There are changes happening that make it not great if people aren't using the more recent versions.

Not sure how to go about implementing it, though. One idea: if the version release timestamp is older than N months (2? 3?) have it check the github repo for newer releases (every N runs?) and write a warning mentioning it.

**Comment by shibumi** [comment]
@mmazur  this would call the GitHub API on every osdctl execution. I have implemented a latest version lookup via `osdctl version` in this PR: https://github.com/openshift/osdctl/pull/194 You might want to comment this :)

**Comment by georgettica** [comment]
@shibumi you should ping @mmazur on internal comms regarding this feat.
I am sure he'll be happy to comment
