### ISSUE TITLE
Have `account console` set up correct region

### ISSUE THREAD

**Issue by mmazur** [openshift/osdctl#182]
The url generated looks like this:
```
The AWS Console URL is:
https://signin.aws.amazon.com/federation?Action=login&Destination=https%3A%2F%2Fconsole.aws.amazon.com%2F&Issuer=Red+Hat+SRE&SigninToken=
```

My quick testing shows that if you modify the `Destination` to point to `https://$REGION.console.aws.amazon.com` that logs directly into the desired region.

If somebody could confirm that's indeed the case, then this should be a 5 lines patch.

**Comment by georgettica** [comment]
/close
This is in the latest release and works
