### ISSUE TITLE
Extract client libraries to enable faster command development 

### ISSUE THREAD

**Issue by georgettica** [openshift/osdctl#198]
Currently I tried to run https://github.com/openshift/osdctl/pull/189 and found that it was conplex for me to add the ocm client in.

I would like that the
- ocm
- AWS
- k8s
Libraries will have a package each and I could run in the command code
```
a, err:= aws.NewAwsClient()
if err !=nil {
  return err
}
```

It's important that the func won't require any args as this will make pulling the client much faster

**Comment by georgettica** [comment]
cc @cblecker

**Comment by fahlmant** [comment]
@georgettica Can you please create an OSD for this instead of an issue?

**Comment by georgettica** [comment]
There is an odd card for this, but am AFK so cannot link it here

**Comment by fahlmant** [comment]
Ack. Closing since there's already an OSD
