### ISSUE TITLE
region is always defaulting to UsEast1RegionID

### ISSUE THREAD

**Issue by T0MASD** [openshift/osdctl#212]
I'm using osdctl to access account console using -r option, however it's always defaulting to us-east-1 
This is getting set in https://github.com/openshift/osdctl/blob/master/pkg/k8s/clusterresourcefactory.go#L155 it should really be respecting the -r option

**Comment by mjlshen** [comment]
Looks like I erroneously added this logic here: https://github.com/openshift/osdctl/pull/199/files#diff-9307e1f146cb2f7a0d0d89406acfaa6d3e2477a52484dfe18b4a9ab09d40a0e9R150-R156

**Comment by fahlmant** [comment]
Please use OSD cards for this in the future
