### ISSUE TITLE
`osdctl account cli -o json` in 0.9.6 does not produce valid json

### ISSUE THREAD

**Issue by mmazur** [openshift/osdctl#229]
This in turn breaks our internal scripts (chgm and provdelay).

Update:
`osdctl` appears to produce a `running the command` info line, which breaks outputs. Example:

```
$ ./osdctl account cli -p rhcontrol -C 1tgqiqb6asdfasdfasdfasdfasdfasdf -o json
running the command: 'ocm list clusters --parameter=search="((id like '1tgqiqb6asdfasdfasdfasdfasdfasdf' or external_id like '1tgqiqb6asdfasdfasdfasdfasdfasdf' or display_name like '1tgqiqb6asdfasdfasdfasdfasdfasdf))"'
{
"AccessKeyId":
````

I suspect this might be a universal issue for all output formats and all commands.

**Comment by fahlmant** [comment]
Can you specify the error you get?

**Comment by mmazur** [comment]
Yup, now that Monday's upon us, I looked into it and updated the case.

**Comment by shibumi** [comment]
I really wonder how this can happen, do we print JSON without `json.Marshal` somewhere in the code? oO
`json.Marshal` should never produce invalid JSON like this.

**Comment by fahlmant** [comment]
This has been fixed on the `master` branch
