### ISSUE TITLE
Problem with encoding or accented characters

### ISSUE THREAD

**Issue by lucmp** [openshift/osdctl#242]
I've always had this problem with osdsh/osdctl:

```
$ osdctl -s 'test'
test
$ osdctl -s 'sermão'
serm
$ osdctl -s 'fácil'
f
$ osdctl -s 'ótimo'
[empty]
```

So the output always dies off at the accented character and nothing else after it is printed.

(Obviously, the output is displayed as on screen text, not in terminal output.)

I have a Tcl script sending text to osdctl and I can convert the text to other encodings before sending it to osdctl. But none of the encodings work. The output is exactly the same unless I convert the text to ascii, in which case osdctl displays each accented character as '?' instead of printing incomplete output.

There is no mention of encodings in either manual and a google search didn't help either.

Can you please provide some information on that? Is there any encoding that osdsh/osdctl will understand and comply with?

**Comment by fahlmant** [comment]
Hi @lucmp!
Thank you for the feedback. However, I believe you're looking for another osdctl: https://manpages.ubuntu.com/manpages/focal/man1/osdctl.1.html
This repo, openshift/osdctl is a different tool than the one you're asking about.
